/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/demo': RouteRecordInfo<'/demo', '/demo', Record<never, never>, Record<never, never>>,
    '/forget-password': RouteRecordInfo<'/forget-password', '/forget-password', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my/': RouteRecordInfo<'/my/', '/my', Record<never, never>, Record<never, never>>,
    '/product/': RouteRecordInfo<'/product/', '/product', Record<never, never>, Record<never, never>>,
    '/product/[id]': RouteRecordInfo<'/product/[id]', '/product/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/team/': RouteRecordInfo<'/team/', '/team', Record<never, never>, Record<never, never>>,
  }
}
